backend:
  name: "github"
  auth_scope: "public_repo"
  # NOTE: branch is set programmatically in admin.astro
  repo: "brunoRoemers/roemers.io-v3"
media_folder: "src/assets/uploads"
public_folder: "/src/assets/uploads"
local_backend: true
collections:
  - name: 'projects'
    label: 'Projects'
    folder: "src/content/projects"
    slug: "{{slug}}"
    summary: "{{title}}"
    preview_path: projects/{{slug}}
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
  - name: 'posts'
    label: 'Posts'
    folder: "src/content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}}"
    preview_path: posts/{{slug}}
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Content
        widget: markdown